// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/hydr0g3nz/wallet_topup_system/internal/adapter/ent/schema"
	"github.com/hydr0g3nz/wallet_topup_system/internal/adapter/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTransactionID is the schema descriptor for transaction_id field.
	userDescTransactionID := userFields[0].Descriptor()
	// user.TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	user.TransactionIDValidator = userDescTransactionID.Validators[0].(func(string) error)
	// userDescSourceTransactionID is the schema descriptor for source_transaction_id field.
	userDescSourceTransactionID := userFields[1].Descriptor()
	// user.SourceTransactionIDValidator is a validator for the "source_transaction_id" field. It is called by the builders before save.
	user.SourceTransactionIDValidator = userDescSourceTransactionID.Validators[0].(func(string) error)
	// userDescTerminalID is the schema descriptor for terminal_id field.
	userDescTerminalID := userFields[2].Descriptor()
	// user.TerminalIDValidator is a validator for the "terminal_id" field. It is called by the builders before save.
	user.TerminalIDValidator = userDescTerminalID.Validators[0].(func(string) error)
}
