// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hydr0g3nz/wallet_topup_system/internal/adapter/ent/predicate"
	"github.com/hydr0g3nz/wallet_topup_system/internal/adapter/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks     []Hook
	mutation  *UserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetTransactionID sets the "transaction_id" field.
func (uu *UserUpdate) SetTransactionID(s string) *UserUpdate {
	uu.mutation.SetTransactionID(s)
	return uu
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableTransactionID(s *string) *UserUpdate {
	if s != nil {
		uu.SetTransactionID(*s)
	}
	return uu
}

// SetSourceTransactionID sets the "source_transaction_id" field.
func (uu *UserUpdate) SetSourceTransactionID(s string) *UserUpdate {
	uu.mutation.SetSourceTransactionID(s)
	return uu
}

// SetNillableSourceTransactionID sets the "source_transaction_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableSourceTransactionID(s *string) *UserUpdate {
	if s != nil {
		uu.SetSourceTransactionID(*s)
	}
	return uu
}

// SetTerminalID sets the "terminal_id" field.
func (uu *UserUpdate) SetTerminalID(s string) *UserUpdate {
	uu.mutation.SetTerminalID(s)
	return uu
}

// SetNillableTerminalID sets the "terminal_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableTerminalID(s *string) *UserUpdate {
	if s != nil {
		uu.SetTerminalID(*s)
	}
	return uu
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.TransactionID(); ok {
		if err := user.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "User.transaction_id": %w`, err)}
		}
	}
	if v, ok := uu.mutation.SourceTransactionID(); ok {
		if err := user.SourceTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "source_transaction_id", err: fmt.Errorf(`ent: validator failed for field "User.source_transaction_id": %w`, err)}
		}
	}
	if v, ok := uu.mutation.TerminalID(); ok {
		if err := user.TerminalIDValidator(v); err != nil {
			return &ValidationError{Name: "terminal_id", err: fmt.Errorf(`ent: validator failed for field "User.terminal_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (uu *UserUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUpdate {
	uu.modifiers = append(uu.modifiers, modifiers...)
	return uu
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.TransactionID(); ok {
		_spec.SetField(user.FieldTransactionID, field.TypeString, value)
	}
	if value, ok := uu.mutation.SourceTransactionID(); ok {
		_spec.SetField(user.FieldSourceTransactionID, field.TypeString, value)
	}
	if value, ok := uu.mutation.TerminalID(); ok {
		_spec.SetField(user.FieldTerminalID, field.TypeString, value)
	}
	_spec.AddModifiers(uu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTransactionID sets the "transaction_id" field.
func (uuo *UserUpdateOne) SetTransactionID(s string) *UserUpdateOne {
	uuo.mutation.SetTransactionID(s)
	return uuo
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableTransactionID(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetTransactionID(*s)
	}
	return uuo
}

// SetSourceTransactionID sets the "source_transaction_id" field.
func (uuo *UserUpdateOne) SetSourceTransactionID(s string) *UserUpdateOne {
	uuo.mutation.SetSourceTransactionID(s)
	return uuo
}

// SetNillableSourceTransactionID sets the "source_transaction_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableSourceTransactionID(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetSourceTransactionID(*s)
	}
	return uuo
}

// SetTerminalID sets the "terminal_id" field.
func (uuo *UserUpdateOne) SetTerminalID(s string) *UserUpdateOne {
	uuo.mutation.SetTerminalID(s)
	return uuo
}

// SetNillableTerminalID sets the "terminal_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableTerminalID(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetTerminalID(*s)
	}
	return uuo
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.TransactionID(); ok {
		if err := user.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "User.transaction_id": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.SourceTransactionID(); ok {
		if err := user.SourceTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "source_transaction_id", err: fmt.Errorf(`ent: validator failed for field "User.source_transaction_id": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.TerminalID(); ok {
		if err := user.TerminalIDValidator(v); err != nil {
			return &ValidationError{Name: "terminal_id", err: fmt.Errorf(`ent: validator failed for field "User.terminal_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (uuo *UserUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUpdateOne {
	uuo.modifiers = append(uuo.modifiers, modifiers...)
	return uuo
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.TransactionID(); ok {
		_spec.SetField(user.FieldTransactionID, field.TypeString, value)
	}
	if value, ok := uuo.mutation.SourceTransactionID(); ok {
		_spec.SetField(user.FieldSourceTransactionID, field.TypeString, value)
	}
	if value, ok := uuo.mutation.TerminalID(); ok {
		_spec.SetField(user.FieldTerminalID, field.TypeString, value)
	}
	_spec.AddModifiers(uuo.modifiers...)
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
